# Generated by Django 5.2.12 on 2026-04-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=128, unique=True)),
                ('license_type', models.CharField(choices=[('monthly', '1 month'), ('yearly', '1 year'), ('lifetime', 'Lifetime')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hardware_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('license_check', 'License check'), ('activation', 'Activation'), ('z_report_sync', 'Z-report sync'), ('error', 'Error')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('client_event_id', models.CharField(blank=True, max_length=120, null=True)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='licenses.license')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='stores.store')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('store',), name='unique_active_license_per_store'),
        ),
        migrations.AddConstraint(
            model_name='systemlog',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('store', 'client_event_id'), name='uniq_store_client_event_id'),
        ),
    ]
