# Generated by Django 5.2.12 on 2026-04-30 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='event_type',
            field=models.CharField(choices=[('license_check', 'License check'), ('activation', 'Activation'), ('z_report_sync', 'Z-report sync'), ('backup_upload', 'Backup upload'), ('error', 'Error')], max_length=40),
        ),
        migrations.CreateModel(
            name='ClientBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(max_length=255, unique=True)),
                ('backup_file', models.FileField(upload_to='backups/')),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='licenses.license')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_backups', to='stores.store')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
