server {
    listen 80;
    server_name your-domain.com www.your-domain.com;

    client_max_body_size 20M;

    location /static/ {
        alias /var/www/geeks_pos_dashboard/staticfiles/;
        expires 30d;
        access_log off;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn/geeks_pos_dashboard.sock;
        proxy_read_timeout 90;
        proxy_connect_timeout 60;
        proxy_send_timeout 90;
    }
}
